/**
 * Type declarations for .proto file imports
 * The Hallow plugin transforms .proto imports into TypeScript stub classes
 */

declare module '*.proto' {
  import type { GrpcWebClient } from '@hallow/grpc-web';

  // Export generated stub classes
  // These will be generated by @hallow/plugin at build time
  export const GreetingServiceStub: any;
  export default GreetingServiceStub;
}
