// Generated by Hallow gRPC generator

import { grpc } from '@improbable-eng/grpc-web';
import { BrowserHeaders } from 'browser-headers';

export interface GetUserRequest {
  user_id: string;
}

export interface GetUserResponse {
  id: string;
  name: string;
  email: string;
}

export interface ListUsersRequest {
  page_size: number;
  page_token: string;
}

export interface ListUsersResponse {
  users: GetUserResponse[];
  next_page_token: string;
}

export interface CreateUserRequest {
  name: string;
  email: string;
}

export interface StreamMessage {
  content: string;
  timestamp: number;
}

export class UserServiceClient {
  constructor(private hostname: string, private options?: any) {}

  GetUser(
    request: GetUserRequest,
    metadata?: grpc.Metadata
  ): Promise<GetUserResponse> {
    return new Promise((resolve, reject) => {
      // Implementation would go here
      // This is a simplified example
    });
  }

  ListUsers(
    request: ListUsersRequest,
    metadata?: grpc.Metadata
  ): Promise<ListUsersResponse> {
    return new Promise((resolve, reject) => {
      // Implementation would go here
      // This is a simplified example
    });
  }

  CreateUsers(
    request: CreateUserRequest,
    metadata?: grpc.Metadata
  ): Promise<ListUsersResponse> {
    return new Promise((resolve, reject) => {
      // Implementation would go here
      // This is a simplified example
    });
  }

  Chat(
    request: StreamMessage,
    metadata?: grpc.Metadata
  ): Promise<StreamMessage> {
    return new Promise((resolve, reject) => {
      // Implementation would go here
      // This is a simplified example
    });
  }

}
