[package]
name = "hallow-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Note: SWC dependencies require Rust 1.82+
# These will be added when Rust is updated:
# swc_core = { version = "0.80", features = ["ecma_plugin_transform"] }