/**
 * Type definitions for Hallow React hooks
 */

import {
  ITransportAdapter,
  MethodDescriptor,
  CallOptions,
  AdapterConfig,
} from '@hallow/generator/adapters';

/**
 * Configuration for adapter used by hooks
 * Extends AdapterConfig with adapter type selection
 */
export interface HookAdapterConfig extends AdapterConfig {
  /**
   * Preferred adapter type
   * - 'grpc-web': Always use grpc-web adapter
   * - 'native': Always use native gRPC adapter (requires Node.js)
   * - 'auto': Automatically select based on environment (default)
   *
   * @default 'auto'
   */
  adapterType?: 'grpc-web' | 'native' | 'auto';

  /**
   * Enable native gRPC in Node.js environments
   * When false, forces use of grpc-web even in Node.js
   *
   * @default true
   */
  enableNativeGrpc?: boolean;
}

/**
 * Result of useGrpc hook
 */
export interface UseGrpcResult<TResponse> {
  /**
   * Response data from the RPC call
   * Undefined while loading or if error occurred
   */
  data: TResponse | undefined;

  /**
   * Error if the call failed
   */
  error: Error | undefined;

  /**
   * Whether the call is in progress
   */
  loading: boolean;

  /**
   * Manually trigger a refetch of the data
   */
  refetch: () => void;
}

/**
 * Result of useGrpcStream hook
 */
export interface UseGrpcStreamResult<TResponse> {
  /**
   * Array of all messages received so far
   */
  messages: TResponse[];

  /**
   * Latest message received
   */
  latestMessage: TResponse | undefined;

  /**
   * Error if the stream failed
   */
  error: Error | undefined;

  /**
   * Whether the stream is currently active
   */
  streaming: boolean;

  /**
   * Whether the stream has completed
   */
  completed: boolean;

  /**
   * Cancel the stream
   */
  cancel: () => void;

  /**
   * Restart the stream
   */
  restart: () => void;
}

/**
 * Factory function to create a service stub
 * This is typically generated by the code generator
 */
export type StubFactory<T> = (
  adapter: ITransportAdapter
) => T;

/**
 * Function that takes a stub and returns a call result
 */
export type StubMethod<TStub, TResponse> = (
  stub: TStub
) => Promise<TResponse>;

/**
 * Function that takes a stub and returns a streaming call
 */
export type StreamingStubMethod<TStub, TResponse> = (
  stub: TStub
) => { subscribe: (observer: StreamObserver<TResponse>) => { unsubscribe: () => void } };

/**
 * Observer for streaming responses
 */
export interface StreamObserver<TResponse> {
  next?: (value: TResponse) => void;
  error?: (err: Error) => void;
  complete?: () => void;
}
