const fs = require('fs');
const path = require('path');
const {
  createServiceGenerator,
  createMessageGenerator,
  createImportManager,
  createNameResolver
} = require('../generator/dist/index.js');

// Read proto file
const protoPath = path.join(__dirname, 'src/service.proto');
const protoContent = fs.readFileSync(protoPath, 'utf-8');

// Simple proto parser (for demonstration)
// In real implementation, this would use the parser package
function parseProto(content) {
  const services = [];
  const messages = [];

  // Extract package name
  const packageMatch = content.match(/package\s+([^;]+);/);
  const packageName = packageMatch ? packageMatch[1] : '';

  // Extract service definitions
  const serviceRegex = /service\s+(\w+)\s*{([^}]+)}/g;
  let serviceMatch;
  while ((serviceMatch = serviceRegex.exec(content)) !== null) {
    const serviceName = serviceMatch[1];
    const serviceBody = serviceMatch[2];

    const methods = [];
    const methodRegex = /rpc\s+(\w+)\s*\(([^)]+)\)\s+returns\s+\(([^)]+)\)/g;
    let methodMatch;
    while ((methodMatch = methodRegex.exec(serviceBody)) !== null) {
      methods.push({
        name: methodMatch[1],
        inputType: methodMatch[2].replace(/stream\s+/, ''),
        outputType: methodMatch[3].replace(/stream\s+/, ''),
        clientStreaming: methodMatch[2].includes('stream'),
        serverStreaming: methodMatch[3].includes('stream')
      });
    }

    services.push({ name: serviceName, methods });
  }

  // Extract message definitions
  const messageRegex = /message\s+(\w+)\s*{([^}]+)}/g;
  let messageMatch;
  while ((messageMatch = messageRegex.exec(content)) !== null) {
    const messageName = messageMatch[1];
    const messageBody = messageMatch[2];

    const fields = [];
    const fieldRegex = /(repeated\s+)?(\w+)\s+(\w+)\s*=\s*(\d+);/g;
    let fieldMatch;
    while ((fieldMatch = fieldRegex.exec(messageBody)) !== null) {
      fields.push({
        repeated: !!fieldMatch[1],
        type: fieldMatch[2],
        name: fieldMatch[3],
        number: parseInt(fieldMatch[4])
      });
    }

    messages.push({ name: messageName, fields });
  }

  return {
    package: packageName,
    services,
    messages
  };
}

try {
  // Parse proto file
  const proto = parseProto(protoContent);

  // Generate code without using the complex generators
  // This simulates what the Hallow generator would produce
  let generatedCode = '// Generated by Hallow gRPC generator\n\n';

  // Add imports
  generatedCode += `import { grpc } from '@improbable-eng/grpc-web';\n`;
  generatedCode += `import { BrowserHeaders } from 'browser-headers';\n\n`;

  // Generate message interfaces
  for (const message of proto.messages) {
    generatedCode += `export interface ${message.name} {\n`;
    for (const field of message.fields) {
      const tsType = field.type === 'string' ? 'string' :
                      field.type === 'int32' || field.type === 'int64' ? 'number' :
                      field.type === 'bool' ? 'boolean' : field.type;
      generatedCode += `  ${field.name}: ${field.repeated ? `${tsType}[]` : tsType};\n`;
    }
    generatedCode += '}\n\n';
  }

  // Generate service client
  for (const service of proto.services) {
    generatedCode += `export class ${service.name}Client {\n`;
    generatedCode += `  constructor(private hostname: string, private options?: any) {}\n\n`;

    for (const method of service.methods) {
      generatedCode += `  ${method.name}(\n`;
      generatedCode += `    request: ${method.inputType},\n`;
      generatedCode += `    metadata?: grpc.Metadata\n`;
      generatedCode += `  ): Promise<${method.outputType}> {\n`;
      generatedCode += `    return new Promise((resolve, reject) => {\n`;
      generatedCode += `      // Implementation would go here\n`;
      generatedCode += `      // This is a simplified example\n`;
      generatedCode += `    });\n`;
      generatedCode += `  }\n\n`;
    }

    generatedCode += '}\n';
  }

  // Write generated code to file
  const outputPath = path.join(__dirname, 'src/generated.ts');
  fs.writeFileSync(outputPath, generatedCode);

  console.log('✅ Generated TypeScript code written to:', outputPath);
  console.log('   Package:', proto.package);
  console.log('   Services:', proto.services.map(s => s.name).join(', '));
  console.log('   Messages:', proto.messages.map(m => m.name).join(', '));

} catch (error) {
  console.error('❌ Error generating code:', error);
}